export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const MODIFY_PLAYER_SUCCESS = 'MODIFY_PLAYER_SUCCESS';
export const ADD_EDIT_PLAYER = 'ADD_EDIT_PLAYER';
